<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.15.1" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
	  <!-- ✅ After -->
	  <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="9.10.0" />
	  <PackageReference Include="MimeKit" Version="4.15.1" />
	  <PackageReference Include="OpenAI" Version="2.10.0" />
	  <PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
	  <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
	  <PackageReference Include="System.Net.Security" Version="4.3.2" />
	  <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
	  <PackageReference Include="OllamaSharp" Version="5.4.25" />
            <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.10.0" />

	  <PackageReference Include="Yoyo.Abp.MailKit" Version="9.1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
